### PR TITLE
include and shade MinigameCore API

### LINKED ISSUE #14: include MinigameCore API dependency
depends on #12

### PR DESCRIPTION
**Pull request by kinggoesgaming**
closes #14

### CODE REVIEW

**Comment by Flibio** [comment]
This doesn't seem to depend on #11, this PR also adds SpongeStart.

**Comment by kinggoesgaming** [comment]
um 
well 
xD

i checked out a new branch from that branch :/

**Comment by kinggoesgaming** [comment]
the reason is that i have specific targets with each PR and dont want to mix them up

**Comment by kinggoesgaming** [comment]
um i realized what i did wrong fixing.. the spongestart line was not supposed to be in this PR at all i copypasta-ed from a private gist :/

**Comment by 12AwsomeMan34** [comment]
Copying comment from https://github.com/MinigameCore/MinigameCore/commit/e1a697bdc25de6450acb6625bf55281bf1c60275#commitcomment-18185939
"Ehm, any reason why you're not just using submodules? Makes things a lot easier. :S"

**Pull request merged**
